apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: nginx
            app.kubernetes.io/name: nginx
            app.kubernetes.io/instance: nginx-cronjob
            app.kubernetes.io/component: cron
        spec:
          containers:
          - name: nginx
            image: nginx:latest
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure