apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  labels:
    app: nginx
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx-daemonset
    app.kubernetes.io/component: web-server
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: nginx-daemonset
        app.kubernetes.io/component: web-server
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always