apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: nginx-job
        app.kubernetes.io/component: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
      dnsPolicy: ClusterFirst
      restartPolicy: Never