apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n4k
  namespace: argocd
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kyverno
    repoURL: https://github.com/nsagark/policy-as-code
    targetRevision: operator-n4k-install
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
