apiVersion: v1
kind: Pod
metadata:
  name: ecr-image-pod
  labels:
    app: nginx
spec:
  containers:
  - name: ecr-container
    image: 197643.dkr.ecr.us-west-2.amazonaws.com/my-repository:tag