apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-pdb
  annotations:
    policies.kyverno.io/title: Generate PodDisruptionBudget
    policies.kyverno.io/category: Availability
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: PodDisruptionBudget
    policies.kyverno.io/description: >-
      This policy automatically generates PodDisruptionBudget resources
      for deployments to ensure high availability during disruptions.
spec:
  rules:
  - name: generate-pdb-for-deployment
    match:
      any:
      - resources:
          kinds:
          - Deployment
    preconditions:
      all:
      - key: "{{ request.object.spec.replicas || '1' }}"
        operator: GreaterThan
        value: 1
    generate:
      apiVersion: policy/v1
      kind: PodDisruptionBudget
      name: "{{request.object.metadata.name}}-pdb"
      namespace: "{{request.object.metadata.namespace}}"
      synchronize: true
      data:
        spec:
          minAvailable: "{{ max(1, round(multiply(request.object.spec.replicas, 0.7))) }}"
          selector:
            matchLabels:
              "{{request.object.spec.selector.matchLabels}}"

  - name: generate-pdb-for-statefulset
    match:
      any:
      - resources:
          kinds:
          - StatefulSet
    preconditions:
      all:
      - key: "{{ request.object.spec.replicas || '1' }}"
        operator: GreaterThan
        value: 1
    generate:
      apiVersion: policy/v1
      kind: PodDisruptionBudget
      name: "{{request.object.metadata.name}}-pdb"
      namespace: "{{request.object.metadata.namespace}}"
      synchronize: true
      data:
        spec:
          minAvailable: "{{ max(1, round(multiply(request.object.spec.replicas, 0.7))) }}"
          selector:
            matchLabels:
              "{{request.object.spec.selector.matchLabels}}" 