apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-network-policies
  annotations:
    policies.kyverno.io/title: Generate Network Policies
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: NetworkPolicy
    policies.kyverno.io/description: >-
      This policy automatically generates NetworkPolicies when a new namespace
      is created to implement zero-trust networking.
spec:
  rules:
  - name: generate-default-deny
    match:
      any:
      - resources:
          kinds:
          - Namespace
    generate:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      name: default-deny-all
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        spec:
          podSelector: {}
          policyTypes:
          - Ingress
          - Egress
  - name: generate-allow-same-namespace
    match:
      any:
      - resources:
          kinds:
          - Namespace
    generate:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      name: allow-same-namespace
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        spec:
          podSelector: {}
          ingress:
          - from:
            - podSelector: {}
          egress:
          - to:
            - podSelector: {}
          policyTypes:
          - Ingress
          - Egress 