apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
  namespace: default  # Violates 'disallow-default-namespace'
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: myregistry.com/myapp:latest  # Violates 'disallow-latest-tag'
      securityContext:
        readOnlyRootFilesystem: false  # Violates 'require-ro-rootfs'
        capabilities:
          add: ["NET_RAW"]  # Violates 'require-drop-cap-net-raw'
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"
        requests:
          memory: "256Mi"
          cpu: "0.5"
      livenessProbe:  # Missing probes violate 'require-probes'
        httpGet:
          path: /healthz
          port: 8080
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
  volumes:
    - name: cri-socket
      hostPath:
        path: /var/run/cri.sock  # Violates 'disallow-cri-sock-mount'

