apiVersion: v1
kind: Pod
metadata:
  name: good-pod
  namespace: production  # Complies with 'disallow-default-namespace'
  labels:
    app: myapp
    environment: production  # Complies with 'require-labels'
    app.kubernetes.io/name: production
spec:
  containers:
    - name: myapp-container
      image: ghcr.io/myapp:v1.0.0  # Complies with 'disallow-latest-tag'
      securityContext:
        readOnlyRootFilesystem: true  # Complies with 'require-ro-rootfs'
        capabilities:
          drop: ["ALL", "CAP_NET_RAW"]  # Complies with 'require-drop-all'
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"
        requests:
          memory: "256Mi"
          cpu: "0.5"
      livenessProbe:  # Complies with 'require-probes'
        httpGet:
          path: /healthz
          port: 8080
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
      startupProbe:
        httpGet:
          path: /startup
          port: 8080
  # No hostPath volumes mounted, complying with 'disallow-cri-sock-mount'

