apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-job
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Never
