apiVersion: batch/v1
kind: CronJob
metadata:
  name: good-cronjob
spec:
  schedule: "*/5 * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: good-cronjob
            image: 58364.dkr.ecr.us-west-2.amazonaws.com/my-repository:tag
            command:
            - sh
            - -c
            - echo "Running cron job"; date; sleep 30