{{- if .Values.kyverno.createCR }}
apiVersion: security.nirmata.io/v1alpha1
kind: KyvernoConfig
metadata:
  annotations:
    {{- if .Values.globalAnnotations }}
    {{- toYaml .Values.globalAnnotations | nindent 4 }}
    {{- end }}
  name: kyverno
  namespace: {{ template "enterprise-kyverno.namespace" . }}
spec: {}

{{- end }}