apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-security-context
  annotations:
    policies.kyverno.io/title: Set Security Context
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy sets security context for containers to enhance
      pod security by running as non-root user and enforcing
      read-only root filesystem.
spec:
  rules:
  - name: set-security-context
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 3000
            fsGroup: 2000
          containers:
            - (name): "*"
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop: ["ALL"] 