annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add a key to preserve configmap settings during upgrade
    - kind: added
      description: Make admission reports breaker threshold configurable
    - kind: added
      description: ImagePullSecrets made globally configurable
    - kind: removed
      description: Deprecated configuration `features.reports.chunkSize` was removed
    - kind: added
      description: ImagePullSecrets made configurable for tests
  artifacthub.io/links: |
    - name: Documentation
      url: https://kyverno.io/docs
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
apiVersion: v2
appVersion: v1.13.4-n4k.nirmata.6
dependencies:
- condition: reports-server.enabled
  name: reports-server
  repository: https://nirmata.github.io/reports-server
  version: 0.1.19
- condition: grafana.enabled
  name: grafana
  repository: ""
  version: 3.3.6
- condition: crds.install
  name: crds
  repository: ""
  version: 3.3.6
description: Kubernetes Native Policy Management
home: https://kyverno.io/
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
keywords:
- kubernetes
- nirmata
- policy agent
- policy
- validating webhook
- admission controller
- mutation
- mutate
- validate
- generate
- supply chain
- security
kubeVersion: '>=1.22.0-0'
maintainers:
- name: Nirmata
  url: https://kyverno.io/
name: kyverno
sources:
- https://github.com/nirmata/enterprise-kyverno
type: application
version: 3.3.14
