apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signature
  annotations:
    policies.kyverno.io/title: Verify Image Signatures
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy verifies container image signatures using cosign.
      It ensures that images are signed by trusted authorities before
      they can be deployed to the cluster.
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: verify-signature
      match:
        any:
        - resources:
            kinds:
            - Pod
      verifyImages:
      - imageReferences:
        - "registry.example.com/*"  # Adjust for your registry
        attestors:
        - entries:
          - keyless:
              subject: "https://github.com/example/.github/workflows/sign.yml@refs/heads/main"  # Adjust for your CI/CD
              issuer: "https://token.actions.githubusercontent.com"
              rekor:
                url: "https://rekor.sigstore.dev"
      - imageReferences:
        - "ghcr.io/*"  # Example for GitHub Container Registry
        attestors:
        - entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                # Add your public key here
                -----END PUBLIC KEY----- 