apiVersion: apps/v1
kind: Deployment
metadata:
  name: signed-app
  labels:
    app: signed-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signed-app
  template:
    metadata:
      labels:
        app: signed-app
    spec:
      containers:
      - name: app
        image: registry.example.com/signed-app:v1.0  # Replace with your signed image
        ports:
        - containerPort: 8080 