name: E2E Tests

permissions:
  contents: write
  
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'ai-remediations'
    paths-ignore:
      - 'remediated-yamls/**'
  pull_request:
    branches:
      - 'ai-remediations'   
    paths-ignore:
      - 'remediated-yamls/**'      
     

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  NCTL-Scan-K8s:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: NCTL install
        run: |
          set -e 
          rm -rf nctl
          mkdir nctl && cd nctl
          curl -LO https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_4.5.0/nctl_4.5.0_linux_amd64.zip
          unzip nctl_4.5.0_linux_amd64.zip
          chmod 755 nctl
          sudo mv nctl /usr/local/bin

      - name: Check nctl version
        run: nctl version

      - name: NCTl login
        run: nctl login --url https://www.nirmata.io --userid sagar@nirmata.com --token ${{ secrets.NIRMATA_TOKEN }}

      - name: Remediation of resources using NCTL
        env:
          GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
        run: |
          git config --global user.name "nsagark"
          git config --global user.email "sagar@nirmata.com" 
          rm -rf remediated-yamls
          
          cp -r resources remediated-yamls;
          nctl scan kubernetes --policies Policies -r remediated-yamls --remediate patch --details -v 10 && echo "NCTL scan passed"
          git add remediated-yamls
          git commit -s -m "remediated resources using AI autoremediation"
          git push
          


       
          
