name: E2E Tests

permissions:
  contents: write
  
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'ai-remediations'
    paths-ignore:
      - 'argo-policies/**'
  pull_request:
    branches:
      - 'ai-remediations'   
    paths-ignore:
      - 'argo-policies/**'      
     

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  NCTL-Scan-K8s:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: nctl-scan-installer
        run: |
          set -e 
          mkdir nctl && cd nctl
          curl -LO https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_4.5.0/nctl_4.5.0_linux_amd64.zip
          unzip nctl_4.5.0_linux_amd64.zip
          chmod 755 nctl
          sudo mv nctl /urs/local/bin

      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Check nctl version
        run: nctl version

      - name: NCTl login
        run: nctl login --url https://www.nirmata.io --userid sagar@nirmata.com --token ${{ secrets.NIRMATA_TOKEN }}
      # - name: NCTL Scan - Kubernetes
      #   run: nctl scan kubernetes --policies controls/pod-security --resources config-files/k8s --audit-as-warn
        
      # - name: NCTL Scan - Kubernetes
      #   run: nctl scan kubernetes --policies controls/pod-security --resources config-files/k8s        

      - name: NCTL Scan - Kubernetes Detailed Report
        run: nctl scan kubernetes --policies controls/pod-security --resources config-files/k8s --details

      # - name: NCTL Scan - Kubernetes Detailed Report
      #   run: nctl scan kubernetes --policies controls/pod-security --resources config-files/k8s --audit-as-warn --details

      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Push policies to cluster via argo
        env:
          GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "nsagark"
          git config user.email "sagar@nirmata.com" 
          cp -r "Policies/disallow-host-namespaces/disallow-host-namespaces.yaml" "argo-policies/"
          git add "argo-policies"
          git commit -m "Copy files to argo folder"
          git push          
          
